### ISSUE TITLE
Does not work if Word is not started as administrator

### ISSUE THREAD

**Issue by RAnders00** [alexandregiordanelli/LatexToWordEquation#2]
Since this application places its temporary files in `C:\` (and that directory is admin-only), word needs to be started as administrator for this addin to work.

Please [use a temporary file](https://stackoverflow.com/questions/581570/how-can-i-create-a-temp-file-with-a-specific-extension-with-net) instead.

**Comment by denuis** [comment]
it doesn't work in my laptop, even started as administrator. Can you fix the problem.  My system is x64 and the office is 2016.

**Comment by jimmyn** [comment]
@alexandregiordanelli Could you please explain how to setup the addon. I've installed it and placed `mathtoweb.jar` to `C:\` but it doesn't work for me, even if I run word as administrator. I'm using Word 2016
